# Generated by Django 4.2 on 2025-03-24 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='noticia',
            table='noticias_noticia',
        ),
    ]
