# Generated by Django 4.2 on 2025-03-24 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_alter_noticia_table'),
    ]

    operations = [
    ]
