# Generated by Django 4.2 on 2025-03-24 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_fix_data_recebimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterModelTable(
            name='noticia',
            table=None,
        ),
    ]
